import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import contactHandler from "./api/contact.js";
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.ALLOWED_ORIGIN || "http://localhost:5173" }));
app.use(express.json());
const adapt = (handler) => (req, res) => { req.query = Object.fromEntries(new URL(req.url, "http://localhost").searchParams); return handler(req, res); };
app.post("/api/contact", adapt(contactHandler));
app.listen(process.env.PORT || 5000, () => console.log(`API running on port ${process.env.PORT || 5000}`));
